sonar.projectKey=kakabi-christian_ProjetTutore
sonar.organization=kakabi-christian

# Sources à analyser (on ratisse un peu plus large pour ne rien rater)
sonar.sources=Backend, Frontend

# On indique ce qu'il ne faut PAS scanner (très important pour ne pas saturer l'analyse)
sonar.exclusions=Backend/vendor/**, Frontend/node_modules/**, Frontend/dist/**, Backend/storage/**, Backend/public/**

# Configuration spécifique pour PHP/Laravel
sonar.php.exclusions=Backend/vendor/**
sonar.php.file.suffixes=php

# Configuration pour Javascript/React
sonar.javascript.file.suffixes=js,jsx,ts,tsx