sonar.projectKey=kakabi-christian_ProjetTutore
sonar.organization=kakabi-christian

# Sources à analyser
sonar.sources=Backend, Frontend

# Exclusions pour éviter de scanner les bibliothèques externes
sonar.exclusions=**/vendor/**, **/node_modules/**, **/dist/**, **/storage/**, **/public/**
############################################################################################3