sonar.projectKey=kakabi-christian_ProjetTutore
sonar.organization=kakabi-christian

# Indique à Sonar où se trouve ton code source
sonar.sources=Backend/app, Backend/routes, Frontend/src

# Langage et encodage
sonar.sourceEncoding=UTF-8