input {
  tcp {
    port => 5044
    codec => json
  }
}

filter {
  # Filtres futurs ici
}

output {
  # 1. Toujours envoyer vers Elasticsearch pour Kibana
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "exchapay-logs-%{+YYYY.MM.dd}"
  }
  
  # 2. ALERTE EMAIL DYNAMIQUE (Utilise ton .env)
  if [level_name] == "ERROR" {
    email {
      to => "${MAIL_FROM_ADDRESS}"
      from => "${MAIL_FROM_ADDRESS}"
      subject => "ALERTE CRITIQUE : Erreur sur l'application ExchaPay !"
      body => "Une erreur a été détectée.\n\nMessage: %{message}\nDate: %{datetime}\nFichier: %{context.file}\nLigne: %{context.line}"
      address => "${MAIL_HOST}"
      port => "${MAIL_PORT}"
      use_tls => true
      username => "${MAIL_USERNAME}"
      password => "${MAIL_PASSWORD}"
    }
  }

  # 3. Debug dans le terminal Docker
  stdout { codec => rubydebug }
}