# k8s/backend-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: exchapay-backend-secrets
type: Opaque
stringData:
  # Avec stringData, Kubernetes encode automatiquement en base64 pour toi
  APP_KEY: "base64:NFgfV1s6ybWcPalb5jW7fmudnVD+No+eiDK7IckNcXA="
  DB_PASSWORD: ""
  MAIL_PASSWORD: "aqutnzsslkljzzzj"
  FLW_PUBLIC_KEY: "FLWPUBK_TEST-b1ded8bcfa20c04ec485c502cd356868-X"
  FLW_SECRET_KEY: "FLWSECK_TEST-63ab9e043ec21546e939afc32f41f5ec-X"
  FLW_ENCRYPTION_KEY: "FLWSECK_TEST8a227f596e19"