# backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: exchapay-backend-service
spec:
  selector:
    app: exchapay-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort