global:
  scrape_interval: 15s # Fréquence à laquelle Prometheus interroge les cibles
  evaluation_interval: 15s

scrape_configs:
  # 1. Prometheus se surveille lui-même (Utilise le nom du service Docker)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # 2. Surveillance de ton application Laravel (ExchaPay API)
  - job_name: 'laravel-backend'
    static_configs:
      - targets: ['backend:8000']

  # 3. Le capteur pour les ressources système (CPU, RAM, Réseau)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']